services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CATALOGS_URL=http://catalogs
      - IAM_URL=http://iam
      - PATIENTS_URL=http://patients
      - EXAMS_URL=http://exams
    networks:
      - microservices-network

  catalogs:
    build: ./catalogs
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=80
    networks:
      - microservices-network

  exams:
    build: ./exams
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=80
      - API_GATEWAY_URL=http://api-gateway:8080
    networks:
      - microservices-network
    depends_on:
      - api-gateway

  iam:
    build: ./iam
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=80
    networks:
      - microservices-network

  patients:
    build: ./patients
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=80
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data: