services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CATALOGS_URL=http://catalogs:8083
    networks:
      - microservices-network
    depends_on:
      - catalogs

  catalogs:
    build: ./catalogs
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOSTNAME=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - microservices-network
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data: