/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
   
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-security:3.2.3")
    implementation(project(":common-security"))
}

// bootJar {
//     enabled = false
// }

// jar {
//     enabled = true
// }
