/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
   
}

dependencies {
 
}

// bootJar {
//     enabled = false
// }

// jar {
//     enabled = true
// }
