# src/main/resources/application.yml
spring:
  application:
    name: exams  # Change this for each service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:labexams}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admingres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081  # Different port for each service

# Eureka Client Configuration
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     preferIpAddress: true
#     instanceId: ${spring.application.name}:${random.uuid}

# Logging Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-at-least-256-bits-long-for-HS256}
  expiration: 36000 # 1 hour in seconds
logging:
  level:
    org:
      hibernate:
        # SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
api:
  gateway:
    url: ${API_GATEWAY_URL:http://localhost:8080}
# Actuator endpoints for monitoring
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#   endpoint:
#     health:
#       show-details: always


# Lab Info

# Laboratory Information Configuration
lab:
  info:
    name: ${LAB_NAME:MedLab Analytics}
    address: ${LAB_ADDRESS:123 Medical Center Drive}
    city: ${LAB_CITY:Healthcare City, Country}
    phone: ${LAB_PHONE:+001 2345678901}
    email: ${LAB_EMAIL:www.medlabanalytics.com}

  # Logo Configuration
  logo:
    path: ${LOGO_PATH:classpath:static/images/logo.png}
    width: 80
    height: 80

