/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")

}



dependencies {
    // Existing dependencies
    implementation("org.springframework.boot:spring-boot-starter-security:3.2.3")
    // implementation("io.jsonwebtoken:jjwt-api:0.12.6")
    // https://mvnrepository.com/artifact/com.auth0/java-jwt
    implementation("com.auth0:java-jwt:4.4.0")

    
    // Add these
    // implementation("io.jsonwebtoken:jjwt-impl:0.12.6")
    // implementation("io.jsonwebtoken:jjwt-jackson:0.12.6")
    
}
