/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")

}



dependencies {
    implementation("org.springframework.boot:spring-boot-starter-security:3.2.3")
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
}
